FROM ubuntu:22.04

LABEL maintainer="ucu-so-labs"

RUN apt-get update && \
    apt-get install -y mysql-server

ENV MYSQL_ROOT_PASSWORD=ucu-so-labs

RUN service mysql start && \
    mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';" && \
    mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "CREATE USER 'docker'@'%' IDENTIFIED BY 'docker';" && \
    mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "GRANT ALL PRIVILEGES ON *.* TO 'docker'@'%';" && \
    mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "FLUSH PRIVILEGES;" && \
    service mysql stop

EXPOSE 3306

CMD ["/usr/sbin/mysqld", "--user=mysql"]